# Add these configurations to your existing _config.yml
execute:
  execute_notebooks: off  # This is already correct
  timeout: 30  # Add timeout setting
  allow_errors: false  # Don't build if there are notebook errors

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_static_path: ['_static']
    html_theme_options:
      repository_url: https://github.com/shreyashguptas/Machine-Learning-for-Dummies
      repository_branch: main
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
    nb_execution_show_tb: True
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add bibtex support if you're using citations
bibtex_bibfiles:
  - references.bib

# Ensure all paths are relative to the book root
latex:
  latex_documents:
    targetname: book.tex

# Add or update these lines in your _config.yml
html:
  use_repository_button: true
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>

# Specify the output directory
output_dir: _build/html