# Book settings
title: Machine Learning for Dummies
author: Shreyash Gupta
copyright: "2024"
logo: images/course-logo.svg

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: off

# Define the build settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: true

# Important: Add these build settings
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_static_path: ['_static']
    html_css_files: []
    html_theme_options:
      repository_url: https://github.com/shreyashgupta/Machine-Learning-Explained-With-Analogies
      repository_branch: main
      use_repository_button: true

repository:
  url: https://github.com/shreyashgupta/Machine-Learning-Explained-With-Analogies
  path_to_book: ""
  branch: main