# Update the existing _config.yml with Jekyll-specific settings
title: Machine Learning for Dummies
author: Shreyash Gupta
description: Learn Machine Learning concepts using simple analogies and practical code examples
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:name

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - requirements.txt
  - requirements-book.yml
  - scripts
  - chapters/*.ipynb