# Book settings
title: Machine Learning for Dummies
author: Shreyash Gupta
copyright: "2024"
logo: images/course-logo.svg

# Repository settings (at root level)
repository:
  url: https://github.com/shreyashguptas/Machine-Learning-for-Dummies
  path_to_book: ""
  branch: main

# Launch button settings
launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic"

# Execution settings
execute:
  execute_notebooks: "off"  # Don't execute notebooks during build
  timeout: 30

# Build settings
only_build_toc_files: true  # Only build files listed in _toc.yml
exclude_patterns: [
  _build,
  Thumbs.db,
  .DS_Store,
  "**.ipynb_checkpoints"
]

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  favicon: "images/course-logo.svg"
  home_page_in_navbar: true

sphinx:
  config:
    html_theme: sphinx_book_theme
    html_static_path: ['_static']
    nb_execution_show_tb: True